--DROP TABLE
drop table if exists bookings cascade ;
drop table if exists bookings_gifts cascade ;
drop table if exists bookings_wishes cascade;
drop table if exists categories cascade;
drop table if exists categories_sub_categories cascade;
drop table if exists complaints cascade;
drop table if exists countries cascade;
drop table if exists gifts cascade;
drop table if exists holidays cascade;
drop table if exists holidays_wishes cascade;
drop table if exists mailing_lists cascade;
drop table if exists notifications cascade;
drop table if exists notifications_types cascade;
drop table if exists request_to_friends cascade;
drop table if exists sub_categories cascade;
drop table if exists  types cascade;
drop table if exists  users cascade;
drop table if exists users_friends cascade;
drop table if exists users_gifts cascade;
drop table if exists users_holidays cascade;
drop table if exists users_wishes cascade;
drop table if exists users_info cascade;
drop table if exists wishes cascade;
-- CREATE TABLE
create table bookings(id int8 not null,user_id int8,primary key (id));
create table bookings_gifts(booking_id int8 not null,gifts_id int8 not null);
create table bookings_wishes(booking_id int8 not null,wishes_id  int8 not null);
create table categories(id int8 not null,name varchar(255),primary key (id));
create table categories_sub_categories(category_id int8 not null,sub_categories_id int8 not null);
create table complaints(id int8 not null,text varchar(255),user_id int8,primary key (id));
create table countries(id int8 not null,name varchar(255),primary key (id));
create table gifts(id int8 not null,date date,description varchar(255),is_block boolean,name varchar(255),photo varchar(255),status varchar(255),booking_id int8,category_id int8,country_id int8,from_user_id int8,user_id int8,primary key (id));
create table holidays(id int8 not null,holiday_date date,is_block boolean,name varchar(255),photo varchar(255),user_id int8,primary key (id));
create table holidays_wishes(holiday_id int8 not null,wishes_id  int8 not null);
create table mailing_lists(id int8 not null,email varchar(255),primary key (id));
create table notifications(id int8 not null,created_at date,is_read boolean,text varchar(255),user_id int8,primary key(id));
create table notifications_types(notification_id int8 not null,types_id int8 not null);
create table request_to_friends(id int8 not null, from_id int8,to_id int8,primary key (id));
create table sub_categories(id int8 not null,name varchar(255),primary key (id));
create table types(id int8 not null,type_status varchar(255),gift_id int8,holiday_id int8,user_id int8,wish_id int8,primary key (id));
create table users(id int8 not null,email varchar(255),first_name varchar(255),friend_status varchar(255),is_block boolean,last_name varchar(255),password varchar(255),role varchar(255),booking_id int8,user_info_id int8,primary key (id));
create table users_friends(user_id int8 not null,friends_id int8 not null);
create table users_gifts(user_id  int8 not null,gifts_id int8 not null);
create table users_holidays(user_id int8 not null,holidays_id int8 not null);
create table users_wishes(user_id int8 not null,wishes_id int8 not null);
create table users_info(id int8 not null,clothing_size varchar(255),country varchar(255),date_of_birth varchar(255),facebook_link varchar(255),hobby varchar(255),important_note varchar(255),instagram_link varchar(255),phone_number varchar(255),photo varchar(1000),shoe_size int4 not null,telegram_link varchar(255),vk_link varchar(255),primary key(id));
create table wishes(id int8 not null,created_at timestamp,description varchar(255),gift_link varchar(255),gift_name varchar(255),gift_photo varchar(255),is_block boolean,is_hidden boolean,wish_date date,booking_id int8,from_user_id int8,holidays_id int8,user_id int8,primary key (id));
-- ALTER ALL TABLE RELATION
alter table if exists bookings_gifts add constraint UK_lg6pkfxj8gyonurbkvwwuy245 unique (gifts_id);
alter table if exists bookings_wishes add constraint UK_efunivux2jsobtv5qrvpdhyo0 unique (wishes_id);
alter table if exists categories_sub_categories add constraint UK_6mli3wnmdahxpo2lwxib2jfg6 unique (sub_categories_id);
alter table if exists holidays_wishes add constraint UK_qs5cwnjgil0uytltl2gyhfm9i unique (wishes_id);
alter table if exists notifications_types add constraint UK_59p1y4i45cddqc6pconuranyf unique (types_id);
alter table if exists users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists users add constraint UK_r53o2ojjw4fikudfnsuuga336 unique (password);
alter table if exists users_friends add constraint UK_eslx46xq9voscm63qgdtr5c28 unique (friends_id);
alter table if exists users_gifts add constraint UK_tn3jh4affar7mfj5xyu7qayvx unique (gifts_id);
alter table if exists users_holidays add constraint UK_hrfliybcett69tndogu2pygl1 unique (holidays_id);
alter table if exists users_wishes add constraint UK_ogl5muaqnw0eny5100kxpn1vf unique (wishes_id);
alter table if exists bookings add constraint FKeyog2oic85xg7hsu2je2lx3s6 foreign key (user_id) references users;
alter table if exists bookings_gifts add constraint FKaifbhysikkcojs4r57sni8kb8 foreign key (gifts_id) references gifts;
alter table if exists bookings_gifts add constraint FKtkwa93e9261fs2esd09jqw9hj foreign key (booking_id) references bookings;
alter table if exists bookings_wishes add constraint FKhqe8grm4m8mh0iohsgd6rswa5 foreign key (wishes_id) references wishes;
alter table if exists bookings_wishes add constraint FK7wmru0f6ebe1e2gmginrj7dn foreign key (booking_id) references bookings;
alter table if exists categories_sub_categories add constraint FK948c1tll7ujo33ipx3dxmyyxa foreign key (sub_categories_id) references sub_categories;
alter table if exists categories_sub_categories add constraint FKj6o2i60fqitfehj72grhcnxtb foreign key (category_id) references categories;
alter table if exists complaints add constraint FK83j5gqkd7ku4vc908g4rtmglr foreign key (user_id) references users;
alter table if exists gifts add constraint FK645vi6gl7kj7n9xiwt3etdvch foreign key (booking_id) references bookings;
alter table if exists gifts add constraint FK8a13qahts004vfuyytaapqyce foreign key (category_id) references categories;
alter table if exists gifts add constraint FKsplobw9s1eeqy1uuq9nd6wb32 foreign key (country_id) references countries;
alter table if exists gifts add constraint FKaa2kh6uw64k5vujegh15o7qp3 foreign key (from_user_id) references users;
alter table if exists gifts add constraint FK9wvjf7q1m4bjdql130h43d1j8 foreign key (user_id) references users;
alter table if exists holidays add constraint FK4e2a1pjumo9ugc2dhwb4d8ec4 foreign key (user_id) references users;
alter table if exists holidays_wishes add constraint FKt4xap81l4b2b8228vmyacwfgn foreign key (wishes_id) references wishes;
alter table if exists holidays_wishes add constraint FKinyxy7j1d29fwcvpsajwgqet7 foreign key (holiday_id) references holidays;
alter table if exists notifications add constraint FK9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references users;
alter table if exists notifications_types add constraint FK8iuumoaaj65407mvnbky3fs9d foreign key (types_id) references types;
alter table if exists notifications_types add constraint FK6ss6dtxxyb0qmo33ka4libqx9 foreign key (notification_id) references notifications;
alter table if exists request_to_friends add constraint FKbtx7dec3fxr7e5dp6c6ni38rs foreign key (from_id) references users;
alter table if exists request_to_friends add constraint FKbq5w8l2fd6m63idx2r47ohsa4 foreign key (to_id) references users;
alter table if exists types add constraint FKb279qr9uf9ettm5v5djjd665h foreign key (gift_id) references gifts;
alter table if exists types add constraint FKlv8w4sns7ya8yxeyen5r7lfu5 foreign key (holiday_id) references holidays;
alter table if exists types add constraint FKe9jhleoesq8lrvbefjx4o7hh foreign key (user_id) references users;
alter table if exists types add constraint FK1miyt36uewbbvm9q4j6up646m foreign key (wish_id) references wishes;
alter table if exists users add constraint FK7ub7p05sq739hx7fxywo8h3a5 foreign key (booking_id) references bookings;
alter table if exists users add constraint FKa4pav0806byoi689xgfobjqic foreign key (user_info_id) references users_info;
alter table if exists users_friends add constraint FKo51ktjiheso8mkdd5n4pdf9f3 foreign key (friends_id) references users;
alter table if exists users_friends add constraint FKry5pun2eg852sbl2l50p236bo foreign key (user_id)  references users;
alter table if exists users_gifts add constraint FKqdsmgmnd26op78o54p9jbwnia foreign key (gifts_id) references gifts;
alter table if exists users_gifts add constraint FK7ukrqy1bctlo19woyt0pu1ppb foreign key (user_id) references users;
alter table if exists users_holidays add constraint FKsctfqe07l96xurjpi9shqwvvs foreign key (holidays_id) references holidays;
alter table if exists users_holidays add constraint FKpgw5thy4psw2ukpmbb6tt54t0 foreign key (user_id) references users;
alter table if exists users_wishes add constraint FKikukdy9fsdmtk791b2xi57h63 foreign key (wishes_id) references wishes;
alter table if exists users_wishes add constraint FKe4vhf0awlw9tj80yfp1jmjuqa foreign key (user_id) references users;
alter table if exists wishes add constraint FKq5urq9dgya7ssh29b7ya2egl4 foreign key (booking_id) references bookings;
alter table if exists wishes add constraint FK7bouwxl23ytlt6jw844ddcin8 foreign key (from_user_id) references users;
alter table if exists wishes add constraint FK30oc38ixe684i5yl32i5bvudt foreign key (holidays_id) references holidays;
alter table if exists wishes add constraint FKh4fwumji30i8f8lt9gnhqxjy7 foreign key (user_id) references users;

-- THIS IS  FOR TEST
insert into users_info(id, clothing_size, country, date_of_birth, facebook_link, hobby, important_note, instagram_link, phone_number, photo, shoe_size, telegram_link, vk_link)
values (1,'XXL','Kyrgyzstan',' 9999-99-99','facebook.com','coding','test','instagram.com','0770-78-65-45','https://www.google.com/search?q=photo&client=safari&rls=en&sxsrf=ALiCzsbPn0T2yUg6QklJu4Zxr4mqO6gL3Q:1659261280321&tbm=isch&source=iu&ictx=1&vet=1&fir=Ypkk3FKI34HKTM%252CB51x0PBR9KNzvM%252C_%253BX5yhXCHDLAHyAM%252CAgAT_yR1X6xrJM%252C_%253BLHC8R68-jkuwQM%252CQvqBvY9dlo_blM%252C_%253B1Hs2MgumyFggtM%252CAgAT_yR1X6xrJM%252C_%253BbrlDatOPf1OADM%252CJ_SUX6tT43D6iM%252C_%253BXYCQ0Av97Hwr0M%252C8XxOuT3U0-dQ9M%252C_%253B1d0KYXzR2E96IM%252CphMLnQWV-ANRGM%252C_%253BVTxC6ACo2sLMvM%252CqXi428qHMy7pCM%252C_%253BVMxxC0JdyRivgM%252CAAWO3YsEJHwgoM%252C_%253BGc5bIChkDaBmKM%252CvP3s60cuDxYZLM%252C_%253B6eDEWe62oo5ggM%252CmvZ9KweEcKGR-M%252C_%253Bm_qMhySJBic00M%252CPIhCb7-LYvyikM%252C_%253B1fVbsXyMCoP5SM%252CAgAT_yR1X6xrJM%252C_%253ByLFkhFfvGDLi6M%252CdP5KNCuNt0yjCM%252C_%253B2_NmP7QZEXEZpM%252C8XxOuT3U0-dQ9M%252C_&usg=AI4_-kRZlfgfxJ2z61QqzTNxPe8HG7aRIQ&sa=X&ved=2ahUKEwj40s_57aL5AhVQtIsKHfD6BeUQ9QF6BAgLEAE#imgrc=VMxxC0JdyRivgM','34','telegram.com','vk.com');
-- THIS IS DEFAULT ADMIN AND USER
insert into users(id, email, first_name, friend_status, is_block, last_name, password, role, booking_id, user_info_id)
values (1,'admin@gmail.com','Admin','FRIEND',true,'Adminov','$2a$12$xEFzerKnyLVgXyBQ/ecOjuVs5rDd2KgixXHHvPSIqTN7TDnRH0Oba','ADMIN',null,1);
